FROM python:3.8

MAINTAINER Jack Grahl <jack.grahl@gmail.com>

# install python and poetry
RUN curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python

# create application directory
RUN mkdir /app
WORKDIR /app

